export const TURN_OFF_OVERLAY = 'TURN_OFF_OVERLAY';
export const TURN_ON_OVERLAY = 'TURN_ON_OVERLAY';
export const TURN_OFF_FIRST_VISIT = "TURN_OFF_FIRST_VISIT";
export const INCR_INSTRUCTIONS_NUMBER = 'INCR_INSTRUCTIONS_NUMBER';
export const STAGE_ONE_CLICKED_ON = "STAGE_ONE_CLICKED_ON";
export const STAGE_ONE_CLEAR_CLICKED_ON = "STAGE_ONE_CLEAR_CLICKED_ON";
