export const TURN_OFF_OVERLAY = 'TURN_OFF_OVERLAY';
export const TURN_ON_OVERLAY = 'TURN_ON_OVERLAY';
export const TURN_OFF_FIRST_VISIT = "TURN_OFF_FIRST_VISIT";
export const INCR_INSTRUCTIONS_NUMBER = 'INCR_INSTRUCTIONS_NUMBER';
