export const TURN_OFF_OVERLAY = 'TURN_OFF_OVERLAY';
export const TURN_ON_OVERLAY = 'TURN_ON_OVERLAY';
export const TURN_OFF_FIRST_VISIT = "TURN_OFF_FIRST_VISIT";
export const INCR_INSTRUCTIONS_NUMBER = 'INCR_INSTRUCTIONS_NUMBER';
//STAGE ONE
export const STAGE_ONE_CLICKED_ON = "STAGE_ONE_CLICKED_ON";
export const STAGE_ONE_CLEAR_CLICKED_ON = "STAGE_ONE_CLEAR_CLICKED_ON";
export const STAGE_ONE_COMPLETED = "STAGE_ONE_COMPLETED";
export const STAGE_ONE_LOST = 'STAGE_ONE_LOST';
export const STAGE_ONE_REVERT_LOST = "STAGE_ONE_REVERT_LOST";
//Stage Two
export const STAGE_TWO_COMPLETED = "STAGE_TWO_COMPLETED";
export const BECOME_CANDIDATE = "BECOME_CANDIDATE";
export const KILL_CANDIDATE = "KILL_CANDIDATE";
//Stage Three
export const STAGE_THREE_CLICKED_ON = "STAGE_THREE_CLICKED_ON";
export const STAGE_THREE_CLEAR_CLICKED_ON = "STAGE_THREE_CLEAR_CLICKED_ON";
export const STAGE_THREE_COMPLETED = "STAGE_THREE_COMPLETED";
export const STAGE_THREE_LOST = 'STAGE_THREE_LOST';
export const STAGE_THREE_REVERT_LOST = "STAGE_THREE_REVERT_LOST";
export const STAGE_THREE_SHUFFLE = "STAGE_THREE_SHUFFLE";

export const REMOVE_CANDIDATE = "REMOVE_CANDIDATE";
export const GAME_LOST = "GAME_LOST";
// Timer 

export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const DECREASRE_SECONDS = "DECREASE_SECONDS";
export const INITIALIZE_TIMER = "INITIALIZE_TIMER";
export const RESET_TIMER = "RESET_TIMER"

//Stage Four
export const STAGE_FOUR_CLICKED_ON = "STAGE_FOUR_CLICKED_ON";
export const STAGE_FOUR_CLEAR_CLICKED_ON = "STAGE_FOUR_CLEAR_CLICKED_ON";
export const STAGE_FOUR_COMPLETED = "STAGE_FOUR_COMPLETED";
export const STAGE_FOUR_LOST = 'STAGE_FOUR_LOST';
export const STAGE_FOUR_REVERT_LOST = "STAGE_FOUR_REVERT_LOST";
export const STAGE_FOUR_SHUFFLE = "STAGE_FOUR_SHUFFLE";
export const STAGE_FOUR_NEW_LIFE = 'STAGE_FOUR_NEW_LIFE';